version: '3.5'
services:
  mariadb:
    image: mariadb:10.5
    restart: always
    container_name: mariadb
    volumes:
      - /data/mariadb/data:/var/lib/mysql
      - /data/mariadb/log:/var/log/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=cryptodb
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      - TZ=Asia/Seoul